#!/usr/bin/env bash

install() {
    # nodejs 10.x
    wget -qO- https://deb.nodesource.com/setup_10.x | sudo -E bash -

    apt update
    apt install -y aria2 nodejs git

    mkdir $HOME/Downloads
    mkdir $HOME/.aria2
    cp ./aria2.conf $HOME/.aria2/

    git clone https://github.com/ziahamza/webui-aria2 && cd webui-aria2
    npm install
}
start() {
    aria2c
    cd ./webui-aria2 && node node-server.js 80 2>1 1>/dev/null &
}
stop() {
    kill -9 `pidof aria2c`
    kill -9 `ps aux | grep node | awk '{print $2}' | head -n 1`
}



if [ -n "$1" ]; then
    case $1 in
        install)
            install
            ;;
        start)
            start
            ;;
        stop)
            stop
            ;;
        restart)
            start
            stop
            ;;
    esac
else
    install
fi

